### ISSUE TITLE
`chalk` is not listed as a dependency

### ISSUE THREAD

**Issue by user202729** [oclif/color#1]
While [`index.ts`](https://github.com/oclif/color/blob/master/src/index.ts#L2) contains the statement

    import chalk from 'chalk'

[`package.json`](https://github.com/oclif/color/blob/master/package.json) does not include it. This causes problems with [`pnpm`'s strict mode](https://www.kochan.io/nodejs/pnpms-strictness-helps-to-avoid-silly-bugs.html).

**Comment by RasPhilCo** [comment]
Closed by https://github.com/oclif/color/commit/6df5f9dfd9eaae0fc1759167d683f0d1972c51f6
