### ISSUE TITLE
@oclif/color  0.1.0 - 0.1.2     Depends on vulnerable versions of strip-ansi

### ISSUE THREAD

**Issue by Sindhura3** [oclif/color#182]
Please publish a color package that doesn't use the vulnerable strip-ansi version

**Comment by CalemRoelofsSB** [comment]
+1 to this, PR [#191] addresses this but some of the Circle CI jobs seem to have timed-out or otherwise failed

**Comment by Sindhura3** [comment]
@mdonnalley Could you please address this as [the oclif/plugin-plugins uses this](https://github.com/oclif/plugin-plugins/issues/356) and is causing security vulnerability issues on Twilio CLI

**Comment by RodEsp** [comment]
https://github.com/oclif/color/releases/tag/v1.0.1 has been released with this fix.
