### ISSUE TITLE
Bug when calling heroku

### ISSUE THREAD

**Issue by liron-navon** [oclif/color#3]
calling `heroku create my-dino --region us` using an npm script.
results in this error:
```
TypeError: Cannot read property 'dim' of undefined
    at Object.<anonymous> (~/Desktop/my-dino/node_modules/@oclif/color/lib/index.js:10:86)
    at V5.run (~/Desktop/my-dino/node_modules/@oclif/plugin-legacy/lib/index.js:89:31)
    at V5._run (~/Desktop/my-dino/node_modules/@oclif/command/lib/command.js:34:31)
```

**Comment by shazron** [comment]
I am encountering this as well. A new release of `@oclif/color` is needed from the master branch code, which now has the `chalk` dependency.

**Comment by shazron** [comment]
Ultimately the culprit is, when npm installs your cli, it might grab the latest `chalk` version `3.x`. This version is not compatible with the released `@oclif/color` which needs `^2.4.2`

**Comment by RasPhilCo** [comment]
Closed by https://github.com/oclif/color/commit/6df5f9dfd9eaae0fc1759167d683f0d1972c51f6

**Comment by animir** [comment]
This issue just happened on Heroku again
```
remote:        $ heroku maintenance:on
remote: TypeError: Cannot read property 'dim' of undefined
remote:     at Object.<anonymous> (/tmp/build_33c0885252ba51912936743471d488d1/node_modules/@oclif/color/lib/index.js:10:86)
remote:     at V5.run (/tmp/build_33c0885252ba51912936743471d488d1/node_modules/@oclif/plugin-legacy/lib/index.js:89:31)
remote:     at V5._run (/tmp/build_33c0885252ba51912936743471d488d1/node_modules/@oclif/command/lib/command.js:43:31)
```

**Comment by omarryhan** [comment]
I'm also having this issue. On Windows Subsystem Linux (WSL) if that's any help.

**Comment by omarryhan** [comment]
This only happens when I use Heroku's npm package via:

```sh
npm i --save-dev heroku
```

I removed it and used Heroku's standalone installation method. i.e.

```sh
curl https://cli-assets.heroku.com/install.sh | sh
```

and it works now.

**Comment by LyricL-Gitster** [comment]
FWIW, this is still an issue with the latest heroku npm package. This is the only issue I can find that mentions it, so I thought I'd give a bandaid solution for the next person until heroku updates their dependencies. I just had to manually add the resolution for `@oclif/color@npm:0.0.0` to `0.1.0` in our project's package.json to get things working again. [Or, like this for Yarn 2.](https://yarnpkg.com/cli/set/resolution)

**Comment by kanedaaaa** [comment]
Still an issue. @omarryhan solution seems to be the best one.

**Comment by benlind** [comment]
I ran into this when trying to use yarn: `yarn global add heroku`. I switched to npm instead and it worked: `npm install -g heroku`.
